language: generic

compiler:
    - g++

sudo: required

services:
  - docker
  
addons:
  apt:
    packages:
      - wget

before_script:
    #- git clone https://github.com/jcelaya/hdrmerge.git
    #- cd hdrmerge
    #- bash ../check_commit.sh master
    #- 'if [ -e travis.cancel ]; then
    #      exit 0;
    #  fi'

script:
    - cd $TRAVIS_BUILD_DIR
    - sudo docker run -it -v $(pwd):/sources centos:7 bash /sources/mkappimage.sh

after_success:
    - cd $TRAVIS_BUILD_DIR
    - pwd
    - ls -lh
    - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
    #- wget -c https://github.com/aferrero2707/uploadtool/raw/master/remove.sh
    #- TRAVIS_REPO_SLUG="jcelaya/hdrmerge" bash ./remove.sh "nightly" "hdrmerge-git-" ".AppImage"
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
    - bash  ./upload_rotate.sh "continuous" out/*
    #- TRAVIS_REPO_SLUG="jcelaya/hdrmerge" bash  ./upload_rotate.sh "nightly" $TRAVIS_BUILD_DIR/hdrmerge/commit-master.hash >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

