#!/bin/bash

DIR="`dirname \"$0\"`" 
DIR="`( cd \"$DIR\" && readlink -f $(pwd) )`"
echo "DIR: $DIR"
export APPDIR=$DIR
export APPDIRS="${APPDIR}"

#export APPIMAGE_ORIGINAL_LD_PRELOAD=$LD_PRELOAD
#export LD_PRELOAD=$DIR/usr/lib/exec_wrapper.so
#export APPIMAGE_STARTUP_LD_PRELOAD=$LD_PRELOAD


source "$APPDIR/apprun-helper.sh"
save_environment
make_temp_libdir
link_libraries
echo "AILIBDIR=$AILIBDIR"
#export APPDIR2=$AILIBDIR
fix_libxcb_dri3
fix_stdlibcxx
#fix_fontconfig
fix_library "libfontconfig"
fix_library "libfreetype"


export PATH=$DIR/usr/bin:$PATH


#export QML2_IMPORT_PATH=$DIR/usr/lib/qml:$QML2_IMPORT_PATH
#export QT_PLUGIN_PATH=$DIR/usr/lib/qt5/plugins/

export GTK_PATH=$DIR/usr/lib/gtk-2.0 #:$GTK_PATH
echo "GTK_PATH=${GTK_PATH}"

export GTK_IM_MODULE_FILE=$DIR/usr/lib/gtk-2.0:$GTK_PATH
echo "GTK_IM_MODULE_FILE=${GTK_IM_MODULE_FILE}"

export PANGO_LIBDIR=$DIR/usr/lib
echo "PANGO_LIBDIR=${PANGO_LIBDIR}"

#export PYTHONHOME=$DIR/usr/
#export PYTHONPATH=$DIR/usr/share/pyshared/:$PYTHONPATH

export XDG_DATA_DIRS=$DIR/usr/share/:$XDG_DATA_DIRS:/usr/local/share/:/usr/share/

#export PERLLIB=$DIR/usr/share/perl5/:$DIR/usr/lib/perl5/:$PERLLIB

export GSETTINGS_SCHEMA_DIR=$DIR/usr/share/glib-2.0/schemas/:$GSETTINGS_SCHEMA_DIR

#export QT_PLUGIN_PATH=$DIR/usr/lib/qt4/plugins/:$DIR/usr/lib/i386-linux-gnu/qt4/plugins/:$DIR/usr/lib/x86_64-linux-gnu/qt4/plugins/:$DIR/usr/lib32/qt4/plugins/:$DIR/usr/lib64/qt4/plugins/:$DIR/usr/lib/qt5/plugins/:$DIR/usr/lib/i386-linux-gnu/qt5/plugins/:$DIR/usr/lib/x86_64-linux-gnu/qt5/plugins/:$DIR/usr/lib32/qt5/plugins/:$DIR/usr/lib64/qt5/plugins/:$QT_PLUGIN_PATH
#export QT_PLUGIN_PATH=$DIR/usr/lib/qt5/plugins:$QT_PLUGIN_PATH

#export GDK_PIXBUF_MODULEDIR=$DIR/usr/lib/gdk-pixbuf-2.0/loaders
#export GDK_PIXBUF_MODULE_FILE=$DIR/usr/lib/gdk-pixbuf-2.0/loaders.cache
#echo "GDK_PIXBUF_MODULEDIR: $GDK_PIXBUF_MODULEDIR"
#echo "GDK_PIXBUF_MODULE_FILE: $GDK_PIXBUF_MODULE_FILE"
#cat $GDK_PIXBUF_MODULE_FILE

#if [ -e /etc/fonts/fonts.conf ]; then
#  export FONTCONFIG_PATH=/etc/fonts
#fi

#if [ -e /usr/share/X11/xkb ]; then
#  export XKB_CONFIG_ROOT=/usr/share/X11/xkb
#  export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
#fi

#export KDE_FORK_SLAVES=1
#export KDEV_DISABLE_PLUGINS=KDevWelcomePage



init_environment

init_gtk


#cd $DIR/usr

echo "Input parameters: \"$@\""
echo ""
echo "Input File: $1"
ldd "$DIR/usr/bin/hugin"
echo ""
echo "$DIR/usr/bin/hugin \"$@\""
LD_PRELOAD="${APPDIR}/usr/lib/exec_wrapper2.so" "${APPDIR}/usr/bin/hugin" "$@"


rm -rf "$AILIBDIR"
rm -f "$AIPENV"
